name: Deploy to AWS
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual invocation of the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
            
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Use GitHub OIDC provider
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.repository }}
          REF_NAME: ${{ github.ref_name }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          export IMAGE_TAG=${REF_NAME}-${COMMIT_SHA:0:7}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
             --cache-from type=registry,ref=$ECR_REGISTRY/$ECR_REPOSITORY:cache \
             --cache-to type=registry,ref=$ECR_REGISTRY/$ECR_REPOSITORY:cache \
             .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: build
    steps:
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-2
      - name: Deploy to ECS Express Mode
        id: deploy-ecs
        uses: aws-actions/amazon-ecs-deploy-express-service@v1
        with:
            service-name: metrics-prod
            image: ${{ needs.build.outputs.image }}
            container-port: 3838
            execution-role-arn: ${{ secrets.AWS_ROLE }}
            infrastructure-role-arn: ${{ secrets.AWS_ROLE }}
            cpu: "4096" #  "1024"
            memory: "8192" # "2048"
            min-task-count: 1  # 2
            max-task-count: 1  # 25
            auto-scaling-metric: AVERAGE_CPU
            auto-scaling-target-value: 10
            environment-variables: |
              [
                {"name": "ENABLE_NGINX", "value": "true"},
                {"name": "SHINY_WORKERS", "value": "3"}
              ]